# Generated by Django 4.2.2 on 2023-07-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay_out_money',
            name='paypal_email',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pay_out_money',
            name='paypal_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='pay_out_money',
            name='destination_type',
            field=models.CharField(choices=[('bkash', 'bkash Account'), ('paypal', 'Paypal Account'), ('bank', 'Bank Account')], default='bkash', max_length=10),
        ),
    ]
