# Generated by Django 4.2.2 on 2023-07-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pay_out_money_paypal_email_pay_out_money_paypal_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_for_send_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=800)),
            ],
        ),
    ]
